version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8089:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-api
      - react-app

  flask-api:
    build: ./flask-api
    volumes:
      - ./flask-api/app.py:/app/app.py:ro
    ports:
      - 5001:5001
      - 8765:8765

  react-app:
    build: ./react-app
    volumes:
      - ./react-app/src:/app/src:ro
      - ./react-app/public:/app/public:ro
    ports:
      - 1234:1234
